apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: application-service-system
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: application-sample
        appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: devfile-sample-go-basic-
      labels:
        appstudio.openshift.io/application: application-sample
        appstudio.openshift.io/component: devfile-sample-go-basic
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: application-service-system
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-go-basic
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:application-service-system-devfile-sample-go-basic-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:9f5d549dd64aacf10e3baac90972dfd5df788324
        name: docker-build
      podTemplate:
        imagePullSecrets:
        - name: redhat-appstudio-registry-pull-secret
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
