apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic
    app.kubernetes.io/part-of: application-sample
  name: devfile-sample-go-basic
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic
    spec:
      containers:
      - env:
        - name: FOO
          value: foo1
        - name: BAR
          value: bar1
        image: go-image:latest
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 1111
        resources:
          limits:
            cpu: "2"
            memory: 600Mi
            storage: 400Mi
          requests:
            cpu: 600m
            memory: 200Mi
            storage: 200Mi
status: {}
