apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: application-sample
    appstudio.openshift.io/component: devfile-sample-go-basic3
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-go-basic3
  namespace: application-service-system
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_yangcao77_go-basic-no-deploy-file
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/yangcao77/go-basic-no-deploy-file
