apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: application-service-system
spec:
  replicas: 3
  selector: null
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: FOO
          value: BAR
        image: quay.io/redhat-appstudio/user-workload:application-service-system-devfile-sample-go-basic
        name: container-image
        resources:
          limits:
            cpu: "3"
            memory: 500Mi
            storage: 400Mi
          requests:
            cpu: 700m
            memory: 400Mi
            storage: 200Mi
status: {}
