apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: yangcao
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: stephanie-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: nodejs-
      labels:
        build.appstudio.openshift.io/application: stephanie-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: yangcao
    spec:
      params:
      - name: git-url
        value: https://github.com/nodeshift-starters/devfile-sample
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:yangcao-nodejs-$(tt.params.git-revision)
      - name: dockerfile
        value: Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:8e1bdea59a9cbf2a3d8199af74ed4cc1939eebf2
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: nodejs/$(tt.params.git-revision)
    status: {}
status: {}
