apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: 1sample
  namespace: yangcao
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: stephanie-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: 1sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: 1sample-
      labels:
        build.appstudio.openshift.io/application: stephanie-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: 1sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: yangcao
    spec:
      params:
      - name: git-url
        value: https://github.com/yangcao77/devfile-sample-go-basic.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:yangcao-1sample-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:3dddea8074c9fa13e7146e3c5c7d75e4bd8f7bb0
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: 1sample/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
