apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic1
    app.kubernetes.io/part-of: application-sample
  name: devfile-sample-go-basic1j6wv
spec:
  host: route111
  path: /
  port:
    targetPort: 1111
  to:
    kind: Service
    name: devfile-sample-go-basic1
    weight: null
status: {}
