apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1sample
    app.kubernetes.io/part-of: stephanie-app
  name: 1sample
  namespace: yangcao
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: 1sample
status:
  loadBalancer: {}
