apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: http-8081
spec:
  host: route111
  path: /
  port:
    targetPort: 1111
  to:
    kind: Service
    name: devfile-sample-go-basic3
    weight: null
status: {}
